language:
  - c
  - c++
  - python
services:
  - docker
env:
  #matrix:
  - OS_TYPE=centos OS_VERSION=7 GCC_VERSION=4.8
  - OS_TYPE=centos OS_VERSION=7 GCC_VERSION=6

before_install:
  - sudo docker pull msaf1980/${OS_TYPE}${OS_VERSION}-gcc${GCC_VERSION}

script:
 # Run tests in Container
 - sudo docker run --rm=true -v `pwd`:/build:rw msaf1980/${OS_TYPE}${OS_VERSION}-gcc${GCC_VERSION} /bin/bash -c ". /etc/profile && cd /build && ./test.sh"

notifications:
  email: false
